services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=uddyr'
      - 'POSTGRES-USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
